import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdtemp,rm,mkdir} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {createDreamaticExtension,DREAMATIC_PERSONA_TOOL_POLICY,dreamaticPersonaTools} from '../dist/extension.js';
const repo=fileURLToPath(new URL('../../../',import.meta.url));
const obsolete=/\blegacy\b|split-file|write_json|patch_json|execute_image_plan|\bimage_generate(?:_batch)?\b|\bimage_edit(?:_batch)?\b/iu;
function harness(workspace,role){const tools=new Map(),handlers=new Map(),active=[];createDreamaticExtension({workspaceDir:workspace,...(role?{personaPath:join(repo,'.pi/agents',`${role}.md`),parentInvocation:{id:`${role}-test`,agent:role,runId:'demo'}}:{})})({registerTool:t=>tools.set(t.name,t),on:(name,fn)=>handlers.set(name,fn),setActiveTools:names=>active.push(names)});return{tools,handlers,active,async call(name,args={}){const t=tools.get(name);assert.ok(t,name);const r=await t.execute(name,t.prepareArguments?t.prepareArguments(args):args,undefined,undefined,{cwd:repo,model:{id:'mock'}});return name==='use_skill'?r:JSON.parse(r.content[0].text);}};}
async function init(workspace){await harness(workspace).call('run_init',{runIdOverride:'demo',projectTitle:'Product',brief:'Two approved product views',designScopes:[{id:'product',category:'industrial',task:'Product views'}]});}
test('Builder MD and managed tools expose only approved execution, presentation and Skill operations',async()=>{
 const workspace=await mkdtemp(join(tmpdir(),'dreamatic-builder-contract-'));
 try{const md=await readFile(join(repo,'.pi/agents/builder.md'),'utf8');assert.doesNotMatch(md,obsolete);const declared=md.split('allowed_tools:')[1].split('---')[0].match(/- (\w+)/g).map(s=>s.slice(2));assert.deepEqual(dreamaticPersonaTools('builder',declared),DREAMATIC_PERSONA_TOOL_POLICY.builder);
 const b=harness(workspace,'builder');assert.deepEqual([...b.tools.keys()].sort(),DREAMATIC_PERSONA_TOOL_POLICY.builder.filter(n=>!['read','write','edit','ls'].includes(n)).sort());assert.doesNotMatch(JSON.stringify([...b.tools.values()].map(t=>({name:t.name,description:t.description,parameters:t.parameters}))),obsolete);
 for(const name of ['write_json','patch_json','execute_image_plan','image_generate','image_generate_batch','image_edit','image_edit_batch','update_design_context','design_bus_post']){assert.equal(b.tools.has(name),false);assert.equal((await b.handlers.get('tool_call')({toolName:name,input:{}},{cwd:repo})).block,true);}
 }finally{await rm(workspace,{recursive:true,force:true});}
});
test('Builder restores Gallery writes but keeps pure generated HTML read-only',async()=>{
 const workspace=await mkdtemp(join(tmpdir(),'dreamatic-builder-presentation-'));
 try{await init(workspace);const path=join(workspace,'runs/demo/context/design.json');const doc={schemaVersion:2,runId:'demo',revision:1,system:{system_thesis:'Clear view',palette:{},typography:{}},strategy:{design_intent:'A page'},deliverables:[{id:'page',scope_id:'product',category:'industrial',skill_refs:['industrial-design'],file:'artifacts/ui/index.html',kind:'html_page',purpose:'Present product',acceptance_test:'Title is visible',required:true,user_requested:true,presentation:{required:true,access:'embed'},execution:{method:'html_generate',files:[{source:'plan/html/ui/index.html',output:'artifacts/ui/index.html'}],resources:[],interaction_checks:[]}}],presentation:{mode:'html',entry:'artifacts/ui/index.html'}};await writeFile(path,JSON.stringify(doc));const b=harness(workspace,'builder');
 let prompt=await b.handlers.get('before_agent_start')({prompt:'Execute approved work',systemPrompt:''});assert.doesNotMatch(prompt.systemPrompt,obsolete);assert.equal(b.active.at(-1).includes('write'),false);assert.equal(b.active.at(-1).includes('edit'),false);assert.equal((await b.handlers.get('tool_call')({toolName:'write',input:{path:'artifacts/notes.html'}},{cwd:repo})).block,true);
 doc.presentation={mode:'gallery',entry:'artifacts/00-gallery.html'};await writeFile(path,JSON.stringify(doc));await b.handlers.get('before_agent_start')({prompt:'Author Gallery',systemPrompt:''});assert.deepEqual(b.active.at(-1),DREAMATIC_PERSONA_TOOL_POLICY.builder);assert.equal(await b.handlers.get('tool_call')({toolName:'write',input:{path:'artifacts/00-gallery.html',content:'Gallery'}},{cwd:repo}),undefined);
 }finally{await rm(workspace,{recursive:true,force:true});}
});
test('managed Builder executes generation and dependent edits internally, loads Gallery knowledge and finalizes delivery',async()=>{
 const workspace=await mkdtemp(join(tmpdir(),'dreamatic-builder-images-')),originalFetch=globalThis.fetch,originalKey=process.env.DREAMATIC_IMAGE_API_KEY;
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
 try{await init(workspace);const root=harness(workspace),r=harness(workspace,'researcher');await r.call('update_design_context',{changes:{evidence:{target:'Product concept',summary:'No factual claims',official_sources:[],open_questions:[]},findings:'Concept fixture',usageConditions:'No external materials'}});assert.equal((await r.call('commit_design_context')).committed,true);await r.call('design_bus_post',{runId:'demo',type:'research_done',summary:'Research ready'});
 const d=harness(workspace,'designer');await d.call('use_skill',{name:'industrial-design',role:'primary',scopeId:'product',rationale:'Design product views'});
 const item=(id,execution)=>({id,scope_id:'product',skill_refs:['industrial-design'],file:`artifacts/${id}.png`,kind:'image',purpose:'Product view',acceptance_test:'Product is visible',required:true,user_requested:true,presentation:{required:true,access:'embed'},execution});
 await d.call('update_design_context',{changes:{system:{system_thesis:'Recognizable product',palette:{},typography:{}},strategy:{design_intent:'Two product views'},deliverables:[item('hero',{method:'image_generate',prompt_seed:'Approved product front view',negative_prompt_seed:'Watermark',size:'512x512',size_rationale:'Product concept'}),item('side',{method:'image_edit',uses:['hero'],prompt_seed:'Approved product side view',negative_prompt_seed:'Watermark',size:'512x512',size_rationale:'Product concept',referenceImagePaths:['artifacts/hero.png'],diagnosis:'Create the requested side view',changes:['Rotate to the side view'],preserve:['Product shape and palette']})],presentation:{mode:'gallery',entry:'artifacts/00-gallery.html'}}});assert.equal((await d.call('commit_design_context')).committed,true);await d.call('design_bus_post',{runId:'demo',type:'design_spec_ready',summary:'Product views ready',requestedAction:'review'});
 const review=harness(workspace,'reviewer');await review.call('update_design_context',{changes:{assessment:{review_stage:'design_context',verdict:'pass',round:1,summary:'Ready',scores:{},issues:[],resolved_issue_ids:[],remaining_risks:[]}}});assert.equal((await review.call('commit_design_context')).committed,true);await review.call('design_bus_post',{runId:'demo',type:'design_review_pass',summary:'Approved views'});
 process.env.DREAMATIC_IMAGE_API_KEY='isolated-test-key';let calls=0;globalThis.fetch=async()=>{calls++;return new Response(JSON.stringify({data:[{b64_json:png.toString('base64')}]}));};const b=harness(workspace,'builder');assert.equal(b.tools.has('execute_image_plan'),false);assert.equal(b.tools.has('image_edit'),false);assert.equal((await b.call('execute_design_plan',{runId:'demo'})).succeeded,2);assert.equal(calls,2);await b.call('execute_design_plan',{runId:'demo'});assert.equal(calls,2);
 await b.call('use_skill',{name:'showcase-layout',role:'supporting'});await b.call('showcase_template',{runId:'demo',title:'Product views',sections:[{title:'Views',items:[{id:'hero',caption:'Front view'},{id:'side',caption:'Side view'}]}]});assert.equal((await b.call('build_finalize',{runId:'demo'})).ok,true);assert.equal((await root.call('export_package',{runId:'demo'})).ok,true);
 }finally{globalThis.fetch=originalFetch;if(originalKey===undefined)delete process.env.DREAMATIC_IMAGE_API_KEY;else process.env.DREAMATIC_IMAGE_API_KEY=originalKey;await rm(workspace,{recursive:true,force:true});}
});
