import assert from 'node:assert/strict';import test from 'node:test';import {createServer} from 'node:http';import {fileURLToPath} from 'node:url';import {readFile} from 'node:fs/promises';import {build} from 'vite';import {browserExecutable} from '../../../packages/design-agent/dist/html-delivery.js';
test('fixed status displays live receipts without opening tool details and keeps successful thumbnails after completion',{timeout:60000},async t=>{
 const executablePath=await browserExecutable();if(!executablePath){t.skip('Chromium unavailable');return}
 const root=fileURLToPath(new URL('..',import.meta.url)),panel=fileURLToPath(new URL('../src/components/AgentPanel.tsx',import.meta.url)),entry='virtual:run-status';
 const bundle=await build({root,configFile:false,logLevel:'silent',esbuild:{jsx:'automatic'},plugins:[{name:'fixture',resolveId(id){if(id===entry)return id},load(id){if(id===entry)return `import React from 'react';import {createRoot} from 'react-dom/client';import {AgentPanel} from ${JSON.stringify(panel)};const root=createRoot(document.getElementById('root'));window.update=props=>root.render(React.createElement(AgentPanel,{timeline:[],streamingText:'',stopping:false,onSend(){},onStop(){},onAnswerClarification(){},onDismissClarification(){},...props}));window.update({running:true,workflow:[]});`;}}],build:{write:false,rollupOptions:{input:entry},minify:false}});
 const js=bundle.output.find(x=>x.type==='chunk').code,css=await readFile(new URL('../src/styles.css',import.meta.url),'utf8');
 const server=createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/bundle.js'?'text/javascript':req.url==='/style.css'?'text/css':'text/html');res.end(req.url==='/bundle.js'?js:req.url==='/style.css'?css:'<html><head><link rel="stylesheet" href="/style.css"></head><body><div id="root"></div><script type="module" src="/bundle.js"></script></body></html>')});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>{server.closeAllConnections();server.close(resolve)}));
 const {chromium}=await import('playwright-core');const browser=await chromium.launch({executablePath,headless:true});t.after(()=>browser.close());const page=await browser.newPage({viewport:{width:1100,height:800}});await page.goto('http://127.0.0.1:'+server.address().port);
 const event={id:'batch',kind:'tool',status:'running',actor:'Builder',label:'Generated design images',at:new Date(Date.now()-10000).toISOString(),updatedAt:new Date().toISOString(),output:'Image hero: receiving response',imageProgress:{total:3,items:{hero:{ok:true,path:'runs/p/artifacts/hero.png'},detail:{ok:false}}}};
 await page.evaluate(event=>window.update({running:true,workflow:[event]}),event);const status=page.getByRole('region',{name:'Run status'});await status.getByText('Saved: 1 · Failed: 1 · Pending: 1 · Total: 3',{exact:true}).waitFor();assert.equal(await status.locator('img').count(),1);assert.match(await status.textContent(),/receiving response/);assert.match(await status.textContent(),/Last status update/);assert.equal(await page.locator('.workflow-event-card').getAttribute('open'),null);assert.equal(await page.getByText('Pi runtime connected',{exact:true}).count(),0);
 const bounds=await status.boundingBox(),composer=await page.locator('.composer').boundingBox();assert.ok(bounds.y+bounds.height<composer.y);
 await page.evaluate(event=>window.update({running:false,workflow:[{...event,status:'completed'}]}),event);assert.equal(await status.locator('img').count(),1);assert.equal(await status.locator('.run-status-heading').count(),0);
});
