import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { build } from 'vite';
import { browserExecutable } from '../../../packages/design-agent/dist/html-delivery.js';
import { readRuntimeConfig, saveRuntimeConfig } from '../../server/dist/config-store.js';
test('Settings entry opens grouped .env settings; examples, persisted fields, secret retention and validation work', {timeout:60_000}, async(t)=>{
 const executablePath=await browserExecutable();if(!executablePath){t.skip('Chromium unavailable');return;}
 const root=await mkdtemp(join(tmpdir(),'dreamatic-settings-ui-'));const env={};let browser,server;
 try{
 await writeFile(join(root,'.env'),'# Existing configuration\nDREAMATIC_MODEL=old-model\nDREAMATIC_API_KEY=keep-private-key\nDREAMATIC_BASE_URL=https://api.example.com/v1\n');
 const sidebar=fileURLToPath(new URL('../src/components/Sidebar.tsx',import.meta.url)),modal=fileURLToPath(new URL('../src/components/SettingsModal.tsx',import.meta.url)),api=fileURLToPath(new URL('../src/api.ts',import.meta.url)),styles=fileURLToPath(new URL('../src/styles.css',import.meta.url)),entry='virtual:settings-test.jsx';
 const bundle=await build({root:fileURLToPath(new URL('..',import.meta.url)),configFile:false,logLevel:'silent',esbuild:{jsx:'automatic'},plugins:[{name:'settings-test',resolveId(id){if(id===entry)return entry;},load(id){if(id!==entry)return;return `import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{Sidebar}from ${JSON.stringify(sidebar)};import{SettingsModal}from ${JSON.stringify(modal)};import{getRuntimeConfig,saveRuntimeConfig}from ${JSON.stringify(api)};import ${JSON.stringify(styles)};function App(){const[config,setConfig]=useState();return <><div className="navigation-open" style={{height:'100vh',width:250,display:'grid'}}><Sidebar runs={[]} onCreate={()=>{}} onSelectRun={()=>{}} onRenameRun={()=>{}} onDeleteRun={()=>{}} onSettings={async()=>setConfig(await getRuntimeConfig())}/></div>{config&&<SettingsModal initial={config} onClose={()=>setConfig(undefined)} onSave={async next=>{await saveRuntimeConfig(next);setConfig(undefined)}}/>}</>;}createRoot(document.getElementById('root')).render(<App/>);`;} }],build:{write:false,rollupOptions:{input:entry},minify:false}});
 const js=bundle.output.find(item=>item.type==='chunk').code,css=bundle.output.find(item=>item.type==='asset'&&item.fileName.endsWith('.css')).source;
 server=createServer(async(req,res)=>{try{if(req.url==='/bundle.js'){res.setHeader('Content-Type','text/javascript');res.end(js);return;}if(req.url==='/style.css'){res.setHeader('Content-Type','text/css');res.end(css);return;}if(req.url==='/api/config'){let result;if(req.method==='PUT'){const chunks=[];for await(const chunk of req)chunks.push(chunk);result=await saveRuntimeConfig(root,JSON.parse(Buffer.concat(chunks).toString()),env);}else result=await readRuntimeConfig(root,env);res.setHeader('Content-Type','application/json');res.end(JSON.stringify(result));return;}res.setHeader('Content-Type','text/html');res.end('<html><link rel="stylesheet" href="/style.css"><div id="root"></div><script type="module" src="/bundle.js"></script></html>');}catch(error){res.statusCode=400;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({error:error.message}));}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const{chromium}=await import('playwright-core');browser=await chromium.launch({executablePath,headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});page.setDefaultTimeout(5000);await page.goto(`http://127.0.0.1:${server.address().port}`);
 const brand=page.getByRole('button',{name:'DreamaticArt menu',exact:true});await brand.waitFor();
 assert.equal(await page.locator('.profile-area').count(),0);
 await brand.click();const menu=page.getByRole('menu',{name:'DreamaticArt menu'});
 const packageInfo=JSON.parse(await readFile(new URL('../../../package.json',import.meta.url),'utf8'));
 assert.equal(await menu.getByRole('menuitem',{name:'GitHub',exact:true}).getAttribute('href'),`https://github.com/idvxlab/Dreamatic/tree/v${packageInfo.version}`);
 assert.equal(await menu.getByRole('menuitem',{name:'GitHub',exact:true}).getAttribute('target'),'_blank');
 await menu.getByRole('menuitem',{name:'About DreamaticArt'}).click();const about=page.getByRole('dialog',{name:'DreamaticArt',exact:true});await about.waitFor();await about.getByText('Intelligent Design & Innovation Lab',{exact:true}).waitFor();await about.getByText(`Version ${packageInfo.version}`,{exact:true}).waitFor();await page.screenshot({path:'/private/tmp/dreamatic-about.png'});await page.keyboard.press('Escape');assert.equal(await about.count(),0);
 const openSettings=async()=>{await brand.click();await page.getByRole('menuitem',{name:'Settings',exact:true}).click();};await openSettings();
 const dialog=page.getByRole('dialog',{name:'Settings'});await dialog.waitFor();assert.equal(await dialog.getByRole('tab').count(),4);assert.ok(await dialog.locator('.config-example').count()>0);assert.ok(await dialog.getByText(join(root,'.env'),{exact:true}).count());
 await dialog.getByRole('tab',{name:'Reasoning models'}).click();assert.equal(await dialog.getByRole('textbox',{name:'Default reasoning model',exact:true}).inputValue(),'old-model');assert.equal(await dialog.locator('input[type="password"]').inputValue(),'');assert.equal(await dialog.getByText('keep-private-key').count(),0);assert.equal(await dialog.getByRole('textbox',{name:'Orchestrator model',exact:true}).isVisible(),false);await page.screenshot({path:'/private/tmp/dreamatic-settings-desktop.png'});
 await dialog.locator('summary').click();await dialog.getByRole('textbox',{name:'Orchestrator model',exact:true}).fill('override-model');await dialog.locator('summary').click();assert.equal(await dialog.getByRole('textbox',{name:'Orchestrator model',exact:true}).isVisible(),false);
 await dialog.getByRole('textbox',{name:'Default reasoning model',exact:true}).fill('new-model');await dialog.getByRole('textbox',{name:'Reasoning API base URL',exact:true}).fill('invalid-url');await dialog.getByRole('button',{name:'Save configuration'}).click();await dialog.getByRole('alert').waitFor();assert.match(await readFile(join(root,'.env'),'utf8'),/DREAMATIC_MODEL=old-model/);
 await dialog.getByRole('textbox',{name:'Reasoning API base URL',exact:true}).fill('https://api.example.com/v1');await dialog.getByRole('tab',{name:'System parameters'}).click();assert.equal(await dialog.getByRole('spinbutton',{name:'Server port',exact:true}).isVisible(),false);await dialog.locator('summary').click();await dialog.getByRole('spinbutton',{name:'Server port',exact:true}).fill('4321');await dialog.getByRole('tab',{name:'Image model'}).click();assert.equal(await dialog.getByRole('textbox',{name:'Generation endpoint',exact:true}).isVisible(),false);await dialog.locator('summary').click();await dialog.getByRole('textbox',{name:'Generation endpoint',exact:true}).fill('https://api.example.com/v1/images/generations');await dialog.locator('summary').click();await dialog.getByRole('textbox',{name:'Image model',exact:true}).fill('image-model');await dialog.getByRole('button',{name:'Save configuration'}).click();await dialog.waitFor({state:'hidden'});
 const disk=await readFile(join(root,'.env'),'utf8');assert.match(disk,/DREAMATIC_MODEL=new-model/);assert.match(disk,/DREAMATIC_MODEL_ORCHESTRATOR=override-model/);assert.match(disk,/PORT=4321/);assert.match(disk,/DREAMATIC_IMAGE_MODEL=image-model/);assert.match(disk,/DREAMATIC_IMAGE_GENERATION_ENDPOINT=https:\/\/api.example.com\/v1\/images\/generations/);assert.match(disk,/DREAMATIC_API_KEY=keep-private-key/);assert.match(disk,/# Existing configuration/);assert.doesNotMatch(disk,/DREAMATIC_AGENT_RETRY_ATTEMPTS=/);assert.doesNotMatch(disk,/DREAMATIC_MODEL_TURN_TIMEOUT_MS_RESEARCHER=/);
 await openSettings();await page.getByRole('tab',{name:'Reasoning models'}).click();assert.equal(await page.getByRole('textbox',{name:'Default reasoning model',exact:true}).inputValue(),'new-model');await page.getByRole('button',{name:'Close settings'}).click();
 await page.setViewportSize({width:390,height:844});await openSettings();const box=await page.getByRole('dialog',{name:'Settings'}).boundingBox();assert.ok(box.width<=390&&box.height<=844);await page.getByRole('tab',{name:'System parameters'}).click();await page.getByRole('button',{name:'Save configuration'}).scrollIntoViewIfNeeded();assert.ok(await page.getByRole('button',{name:'Save configuration'}).isVisible());await page.screenshot({path:'/private/tmp/dreamatic-settings-mobile.png'});
 }finally{await browser?.close();await new Promise(resolve=>server?server.close(resolve):resolve());await rm(root,{recursive:true,force:true});}
});
